version: '3'
volumes:
    deps:

services:
    app:
        image: node:14
        working_dir: /usr/src/app
        command: npm run start
        ports:
            - 3000:3000
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - .:/usr/src/app
            - deps:/usr/src/app/node_modules
